#!/bin/bash


if [ "$#" -lt 1 ]
then
	echo "Usage: $0 <Filename>"
elif [ "$2" ]
then
	cat <<EOF > $1
		#!/usr/bin/python3
		\"\"\"$2\"\"\"
EOF
	chmod +x "$1"
else
	echo "#!/usr/bin/python3\n
	"""
	"""
	" > "$1"
	chmod +x "$1"
fi
