#!/usr/bin/python3
def safe_print_list_integers(my_list=[], x=0):
    count = 0
    try:
        if any(isinstance(n, int) for n in my_list):
            [print("{:d}".format(num), end="") for num in my_list]
            count += 1
        print()
        return count
    except IndexError:
            raise IndexError("IndexError: list index out of range")
    except:
        pass

