#!/usr/bin/python3
"""
    This module define a function
    that return serialize an object to a dictionary
"""


import json


def class_to_json(obj):
    """
    Serialize an object to a dictionary.
    """
    if isinstance(obj, object):
        return json.dumps(obj.__dict__)
